name       : plasma-nm
version    : 5.18.4.1
release    : 51
source     :
    - https://cdn.download.kde.org/stable/plasma/5.18.4/plasma-nm-5.18.4.1.tar.xz : a7ae36b47c2ee85590b01a1e03fae179d243bb4e718417be0b8e93e7dfc77e6a
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
