name       : plasma-nm
version    : 5.22.2
release    : 70
source     :
    - https://cdn.download.kde.org/stable/plasma/5.22.2.1/plasma-nm-5.22.2.1.tar.xz : af4721d98b2e8d37e503456a16921046a6312f90bbf773d038b0a8c2e57f4df3
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
rundeps    :
    - prison
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
