name       : plasma-nm
version    : 5.10.5
release    : 4
source     :
    - https://download.kde.org/stable/plasma/5.10.5/plasma-nm-5.10.5.tar.xz : 7101d07fb1c64cd45591256e756134f85051966762530d8d5a0a93e3ddac9600
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(NetworkManager)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - kitemviews-devel
    - knotifications-devel
    - kservice-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
