name       : plasma-nm
version    : 5.17.5
release    : 47
source     :
    - https://cdn.download.kde.org/stable/plasma/5.17.5/plasma-nm-5.17.5.tar.xz : 2165e47a0654d17735abc97aec287b46b52a2eafccc3591b667ea2755b731255
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
