name       : plasma-nm
version    : 5.20.5
release    : 63
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.5/plasma-nm-5.20.5.tar.xz : 468df2bf99907382125a4822322d23c71e1a59f792eba497d89483dc94180e18
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kiconthemes-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
rundeps    :
    - prison
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
