name       : plasma-nm
version    : 5.24.3
release    : 80
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.3/plasma-nm-5.24.3.tar.xz : 2cf64e94ed921546bc0be44f50e3490033a353bf3f0ad7a5a513ef5585fc3bfd
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
rundeps    :
    - prison
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
