name       : plasma-nm
version    : 5.24.2
release    : 79
source     :
    - https://cdn.download.kde.org/stable/plasma/5.24.2/plasma-nm-5.24.2.tar.xz : 114ead32c90d521ae0504baee971da71a2c0f1a37d25bbf1868012ed030048cb
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
libsplit   : no
optimize   : lto
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - kdbusaddons-devel
    - kdeclarative-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
rundeps    :
    - prison
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
