name       : plasma-nm
version    : 5.11.1
release    : 6
source     :
    - https://cdn.download.kde.org/stable/plasma/5.11.1/plasma-nm-5.11.1.tar.xz : 37fc1e8f343d61badfd257bd21176df33cc2f279b2850075cc7380723c66e910
license    :
    - GPL-2.0
    - LGPL-2.1
component  : desktop.kde.core
libsplit   : no
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(ModemManager)
    - pkgconfig(NetworkManager)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcompletion-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - kdelibs4support-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knotifications-devel
    - kservice-devel
    - kwallet-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - solid-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
    cd $installdir; qml_cache
