name       : plasma-nm
version    : 5.20.4
release    : 61
source     :
    - https://cdn.download.kde.org/stable/plasma/5.20.4/plasma-nm-5.20.4.tar.xz : 7b4d1026f2caa709a9ae284cd18342d1c573276f9b4c356ef47779dadb8b57cf
homepage   : https://www.kde.org/workspaces/plasmadesktop/
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : desktop.kde.core
libsplit   : no
optimize   : lto
summary    : Plasma applet for managing network connections
description: |
    Plasma applet written in QML for managing network connections.
builddeps  :
    - pkgconfig(ModemManager)
    - pkgconfig(libnm)
    - pkgconfig(openconnect)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kconfigwidgets-devel
    - kdbusaddons-devel
    - kdeclarative-devel
    - ki18n-devel
    - kiconthemes-devel
    - kinit-devel
    - kio-devel
    - knotifications-devel
    - kwallet-devel
    - mobile-broadband-provider-info-devel
    - modemmanager-qt-devel
    - networkmanager-qt-devel
    - plasma-framework-devel
    - prison-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    %qml_cache
